config/routes.rb
Hacklendar::Application.routes.draw do

  resources :diary_entries

end

app/models/diary_entry.rb
class DiaryEntry < ActiveRecord::Base
    attr_accessible :description, :title, :mood


  def self.positive
    where(mood: "happy")
  end  

  validates :description, presence: true
  validates :title, presence: true, uniqueness: true

  def mood_is_happy
  	if Time.now.monday? || Time.now.thursday?
  	 errors.add(:mood_is_happy, "must be happy")
    end
  end		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/diary_entries_controller.rb
class DiaryEntriesController < ApplicationController

	def index
		if params[:day]
			@day = params[:day].to_date
		else
			@day = Date.today
		end	
		@diary_entries = DiaryEntry.where(created_at: @day.beginning_of_day..@day.end_of_day)
		@all_entries = DiaryEntry.where(created_at: @day.beginning_of_month..@day.end_of_month)

		@dates = @all_entries.map do |i|
			i.created_at.to_date
		end	

		@diary_entries_positive = DiaryEntry.positive
		
	end	

	def new
		@diary_entry = DiaryEntry.new
	end

	def create
	@diary_entry = DiaryEntry.new params["diary_entry"]

	if @diary_entry.save
		redirect_to diary_entries_path
	else
		render :new
		end
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diary_entries_helper.rb
module DiaryEntriesHelper
end

app/views/diary_entries/_calendar.html.erb
<h2><%= @day.strftime("%B %Y") %></h2>

<table>
<% (@day.to_date.beginning_of_month.beginning_of_week..@day.to_date.end_of_month.end_of_week).each do |day| %>
	<% if day.monday? %>
		<tr>
	<% end %>	

	<td class="span1">
		<%= link_to day.day, diary_entries_path(day: day) %>
		<% if @dates.include?(day) %>
		&#x2713;
			<% entries = @all_entries.select{|e| e.created_at > day.beginning_of_day && e.created_at < day.end_of_day} %>
			<% positive = entries.any?{|e| e.mood == "happy"} %>
				<% if positive %>
				&#9786
				<% end %>		
		<% end %> 
	</td>
<% end %>
<td class="span2"><%= link_to "Previous month", diary_entries_path(day: @day - 1.month) %></td>
<td class="span2"><%= link_to "Next month", diary_entries_path(day: @day + 1.month) %></td>
</table>

app/views/diary_entries/_form.html.erb
# <%= form_for(@diary_entry) do |f| %>

# 	<% if @diary_entry.errors.any? %>
# 		<h2 style="color:red">Something went wrong</h2>
# 		<% diary_entry.errors.full_messages.each do |error| %>
# 			<p style="color:red"><%= error %></p>
# 		<% end %>
# 	<% end %>

# <div class="field">
# 	<%= f.label :title %><br />
# 	<%= f.text_field :title %><br />
# 	<%= f.label :description %><br />
# 	<%= f.text_area :description %>
# </div>

# <%= f.submit %>		

app/views/diary_entries/index.html.erb
<!-- <h1>Hello from a Rails View</h1>

<p>I have <%= @diary_entries.length %> entries</p>

<p>I have <%= @diary_entries_positive.length %> positive entry</p> -->

<!--<% @diary_entries.each do |d| %>
	<%= d.title %>
	<%= d.description %>

	<% if d.mood == "happy" || d.mood == "joyful" %>
		<div style='color: green'><%= d.mood %></div>
	<% else %>
		<div><%= d.mood %></div>
	<% end %>		
<% end %>

<%= link_to 'Create New Diary Entry', new_diary_entry_path %> -->

<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap 101 Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
    <!-- Responsive -->
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
  </head>
  <body>
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>



<div class="container">

	<%= render "calendar" %>

	<ul class="nav nav-pills">
	  <li class="active">
	    <a href="#">Create</a>
	  </li>
	  <li><a href="#">Diary Entries</a></li>
	  <li><a href="#">About</a></li>
	</ul>

	<div class="page-header">
	<h2>Emily's Hacklendar</h2>
	</div>


	<p>
		<button class="btn btn-info" type="button">
			<%= link_to 'New Diary Entry', new_diary_entry_path %>
		</button>	
	</p>
	<table class="table">
		<td>Title</td>
		<td>Description</td>
		<td>Mood</td>

		<% @diary_entries.each do |d| %>
			<tr>
				<td><%= d.title %></td>
				<td><%= d.description %></td>
				<td><%= d. mood %></td>
			</tr>
		<% end %>
	</table>		

	<%= link_to "Previous day", diary_entries_path(day: Time.zone.now - 1.day) %>
	<%= link_to "Next day", diary_entries_path(day: Time.zone.now + 1.day) %>	


</div> <!-- end class container -->


</html>

app/views/diary_entries/new.html.erb
<%= form_for(@diary_entry) do |f| %>

<% if @diary_entry.errors.any? %>
	<h2 style="color:red">Something went wrong</h2>
	<% @diary_entry.errors.full_messages.each do |error| %>
		<p style="color:red"><%= error %></p>
	<% end %>
<% end %>

<div class="field">
	<%= f.label :title %><br />
	<%= f.text_field :title %><br />
	<%= f.label :description %><br />
	<%= f.text_area :description %>
	<%= f.label :mood %>
	<%= f.select :mood, ["happy", "sad", "mad"] %>
</div>

<%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hacklendar</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>